version: '3.5'
services:
  js-renderer:
    build: .
    volumes:
      - .:/src
    ports:
      - '3000:3000'
    command: npm run start
    environment:
      NODE_ENV: dev
      PORT: 3000